she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('user/<int:pk>', views.AuthorStories.as_view(), name='authorStories'),
    path('<int:pk>/comments', views.AddCommentView.as_view(), name='addComment'),
    path('edit/<int:pk>', views.EditStoryView.as_view(), name='edit')
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path 

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    # author = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
        )
    pub_date = models.DateTimeField()
    content = models.TextField()
    # ok if it's empty, will use placeholder image in its place
    image = models.URLField(null=True, blank=True)

class AddComment(models.Model):
    story = models.ForeignKey(
        NewsStory, related_name="comments", on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        get_user_model(), related_name="comments",
        on_delete=models.CASCADE
        )
    pub_date = models.DateTimeField(auto_now="True")
    content = models.TextField()
    

she_codes_news/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    pass 
# double __ is a python method
    def __str__(self):
        return self.username
    

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory
from .models import AddComment

class StoryForm(ModelForm):
    # ModelForm from django gives us something from dango 
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'image', 'content']
        widgets = {
            'pub_date': forms.DateTimeInput(
                format='%d/%m/%Y %H:%M',
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Select a date',
                    'type': 'datetime-local'
                }
            ),
        }


class AddComment(ModelForm):
    class Meta:
        model = AddComment
        fields = ['content']
    

       
            
        

she_codes_news/users/forms.py
# create two new forms - new user and updating user

from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

# parent form has password already, so it will show up even if we don't specify here
# parent form is in settings.py: line 42    

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']

she_codes_news/news/views.py
from typing import Any
from django.db import models
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm
from users.models import CustomUser
from .forms import AddComment
from django.views.generic import ListView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied


# consider views like request handlers

class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = "all_stories"

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by('-pub_date')[:4]
        context['all_stories'] = NewsStory.objects.all().order_by('-pub_date')
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'


    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['form']=AddComment()
        return context

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyform'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

# create new class to view all stories by a certain author

class AuthorStories(generic.ListView):
    model = NewsStory
    template_name = 'news/authorStories.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.filter(author_id=self.kwargs['pk'])
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().filter(author_id=self.kwargs['pk']).order_by('-pub_date')
        context['author'] = CustomUser.objects.get(id=self.kwargs['pk'])
        return context


# need add comment view

class AddCommentView(generic.CreateView):
    form_class = AddComment
    template_name = 'news/story.html'    
    

    def form_valid(self, form):
        form.instance.author = self.request.user
        pk =self.kwargs.get("pk")
        form.instance.story = get_object_or_404 (NewsStory,pk=pk)
        return super().form_valid(form)
    
 
    def get_success_url(self):
        return reverse_lazy("news:story", kwargs={"pk":self.kwargs.get("pk")})



# Edit Story

# class EditStoryView(generic.edit.UpdateView):
#     model = NewsStory
#     form_class = StoryForm
#     template_name = 'news/edit.html'
#     # fields=['title', 'pub_date', 'image', 'content']
#     success_url = reverse_lazy('news:index')

#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         pk=self.kwargs.get("pk")
#         return super().form_valid(form)


class EditStoryView(LoginRequiredMixin, UpdateView):
    model = NewsStory
    template_name = 'news/edit.html'
    fields=['title', 'pub_date', 'image', 'content']
    context_object_name = 'story'
    success_url = reverse_lazy('news:index')

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.author != self.request.user:
            raise PermissionDenied
        return obj

    
  

    

    

    

she_codes_news/users/views.py
# Create your views here.


from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

she_codes_news/news/templates/news/authorStories.html
{% extends "base.html" %}
{% load static %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}



{% block content %}


<div id="author-container">  
    <h2>stories by {{ author }}</h2>
</div>

        <!-- <img src="{% static '/news/images/placeholder-5.jpg' %}"> -->
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
        <p>No Stories Available </p>
        {% endif %}
    


{% endblock %}

she_codes_news/news/templates/news/comments.html
<!-- tells django that this is the base we are using for the webpage -->
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
    <!-- single brackets for django function -->
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>

{% endblock %}

she_codes_news/news/templates/news/createStory.html
<!-- tells django that this is the base we are using for the webpage -->
{% extends "base.html" %}

{% block content %}

<div class="form-container">
    <h3>Write New Story</h3>
    <form action="" method="post" class="form">
        <!-- single brackets for django function -->
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit">
    </form>
</div>

{% endblock %}

she_codes_news/news/templates/news/index.html
    {% extends 'base.html' %}
    {% load static %}

    {% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
    {% endblock %}
   

    {% block content %}
    <br>
    <!-- <a href="{% url 'news:newStory' %}">Write New Story</a> -->
    <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
                
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    
    <section id="h3-container">
        <h3>All Stories</h3>     
    </section>
    <div id="all-stories">
          
      
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
   
    </div>
    {% endblock %}

she_codes_news/news/templates/news/story.html
<!-- news/templates/news/story.html -->
{% extends "base.html" %}
{% load static %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}



{% block content %}
<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>{{ story.author }}</h4>
    <div id="story-content">

        
        {% if story.image != '' %}
        <img src="{{ story.image }}"> 
            {% else %}
        <img src="https://picsum.photos/600">>
        {% endif %}
        {{ story.content|linebreaks }}

    
    </div>
</div>
    

<div id="edit">

    {% if request.user.is_authenticated %}
    <a href="{% url 'news:edit' story.id %}">Edit Story</a>

    {% endif %}



</div>

<!-- add comment section, if user if authenticated  then add comment -->

<div id="comment">
    <h4>Comments</h4>
    {% for comment in story.comments.all %}
    <p>{{ comment.author }}</p>
    <p>{{ comment.content }}</p>
    <p>{{ comment.pub_date }}</p>

    {% empty %}
    <p>leave the first comment</p>
    {% endfor %}


    {% if request.user.is_authenticated %}
    <h4>Share your thoughts!</h4>

    <form action="{% url 'news:addComment' story.id %}" method="post" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <input type = "submit", value="submit">
    </form>
   {% else %}

   <p>log in or create an account to comment</p>

   {% endif %}

</div>
{% endblock %}



   
     

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if story.image != '' %}
            <img src="{{ story.image }}">
            {% else %}
        <img src="https://picsum.photos/600">
        {% endif %}

        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <a href="{% url 'news:authorStories' story.author.id %} "><h4>{{ story.author }}</h4></a>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
<!-- templates/base.html -->

{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Cindy">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
        
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
        {% block content %}{% endblock %}

    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>

    {% if request.user.is_authenticated %}
        <a href="#">{{ user.username }}</a>
        <a href="{% url 'news:newStory' %}">Write New Story</a>
        <a href="{% url 'logout' %}">Logout</a>
    
    {% else %}
        <a href="{% url 'login' %}">Login to write story</a>
        <a href="{% url 'users:createAccount' %}">Create Account</a>
    {% endif %}
</nav>

she_codes_news/users/templates/users/createAccount.html
<!-- users/templates/users/createAccount.html -->

{% extends 'base.html' %}

{% block content %}


<div class="form-container">
  <h2>Create Account</h2>
  <form method="post" id="createaccount">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Account</button>
  </form>
</div>  
{% endblock %}